### ISSUE TITLE
Requests take a really long time

### ISSUE THREAD

**Issue by simonf2004** [TonyM1958/FoxESS-Cloud#14]
Hello, i ve experimenting with your integration and everything seems to be working great. 
There is one problem though, any request takes about 5-10 seconds to complete.
Does anybody have an idea why that could be?   
Thanks

**Comment by TonyM1958** [comment]
Hi, Its a well known problem with Open API. Fox has not allocated sufficient resources and also runs other processes on the servers. Performance is poor and there are often time-outs between 10am and 10pm UK time where requests take longer than 1 minute and then return an error. After 10pm and before 10am, response times are often less than 1 second.

Open API worked well when first introduced in January but performance has been poor since May. Fox is aware of this and has said they are working on it, but it's now 3 months and little has changed and they have not disclosed what is causing the problem or any plans for resolving this. It very frustrating for developers using their API.
