### ISSUE TITLE
Battery.ipynb no longer reporting 

### ISSUE THREAD

**Issue by Andysmith01a** [TonyM1958/FoxESS-Cloud#18]
As described on Facebook foxess owners page the app tries to load soh which my V1 ECS batteries don't have the capability to report. My batteries are 4x ECS 2900 BMS is version 1.017 slaves are all version 1.12 the app was working fine until the other day.

**Comment by Andysmith01a** [comment]
Please ignore above issue, apparently is now working properly again tvm

**Comment by TonyM1958** [comment]
Thanks.

I pushed an update eariler and another one just now. Although it no longer crashes, there is a chance it does not report the battery capacity or residual correctly. I've also added an estimated SoH based on the data Fox returns.

If you can, please can you run the script again (using v1.7.5) and see what it reports. Please can you also run this additional cell below and paste a screen shot of the contents. I'm particularly interested to see the first 7 characters of the BMS serial number and the BMS firmware version as this will help to identify the correct residual handling.

```
f.batteries
```

**Comment by Andysmith01a** [comment]
V1.7.5 now not reporting anything again. f.batteries script reports as follows 
![Screenshot_20241012-213340](https://github.com/user-attachments/assets/6e8eaf7a-c203-445c-9723-01bcf6294a7e)
![Screenshot_20241012-213340](https://github.com/user-attachments/assets/b6ed7445-93f8-41b2-8768-e3736280fc1b)

**Comment by Andysmith01a** [comment]
V1.7,5 reports as follows 
![Screenshot_20241012-215928](https://github.com/user-attachments/assets/1699989b-87c5-439e-8be0-8d1626e16c3a)

**Comment by Andysmith01a** [comment]
![Uploading Screenshot_20241012-220110.png…]()

**Comment by Andysmith01a** [comment]
![Screenshot_20241012-220110](https://github.com/user-attachments/assets/78c4934a-d8aa-414e-8ac3-c477ba469c6b)

**Comment by TonyM1958** [comment]
OK, thanks for posting the info. Clearly, the problem here is that Fox are returning the ratedCapacity of your battery as 0. HV2600 BMS v1 and v2 both return a value for that. I can check for this to stop the error.

Out of interest, what do you see when you look at the battery at foxesscloud.com? The rated capacity is shown as 'Nominal Capacity' here:

![image](https://github.com/user-attachments/assets/8309860f-f347-4451-b667-cd2ebb53b4e3)

It's also shown in Fox App v2 if you tap the Battery, select Detailed Parameters and then look at Capacity.

**Comment by TonyM1958** [comment]
I've pushed v1.7.6. Hopefully, this will resolve the problem of ratedCapacity being returned as 0 and causing the divide by zero error. Please give this a go and confirm if it now works you when you get a chance.
